package org.demo.kaiaskin.models.mysql.enums;

public enum Type_Produit {
    NETTOYANT_VISAGE,
    TONIQUE,
    SERUM,
    CREME_HYDRATANTE,
    CREME_NUIT,
    MASQUE_VISAGE,
    EXFOLIANT_VISAGE,
    HUILE_VISAGE,
    CREME_SOLAIRES_VISAGE,
    GEL_DOUCHE,
    LAIT_CORPS,
    BEURRE_CORPS,
    GOMMAGE_CORPS,
    HUILE_CORPS,
    CREME_MAINS,
    DEODORANT,
    PARFUM,
    CREME_SOLAIRES_CORPS,
    PRODUIT_ANTI_ACNE,
    PRODUIT_ANTI_AGE,
    PRODUIT_POUR_PEAU_SENSIBLE,
    PRODUIT_POUR_PEAU_GRASSE,
    PRODUIT_POUR_PEAU_SECHE,

    AUTRE
}
